### ISSUE TITLE
[question] are the AM1-BCC partial charges calculated using an open-source software?

### ISSUE THREAD

**Issue by UnixJunkie** [openforcefield/openff-sage#12]
If so, which one?

Although I am not a big fan of AM1-BCC charges: they are conformer dependent, and many ligands
will fail at getting such partial charges; unlike with mmff94...

Thanks!
F.

**Comment by mattwthompson** [comment]
Hey @UnixJunkie - the open-source solution for assigning AM1-BCC charges throughout OpenFF software is `sqm`, which is packaged as a part of AmberTools: https://ambermd.org/AmberTools.php

Here's the specification for that section of Sage (and all other OpenFF force fields to date) which expands some more: https://openforcefield.github.io/standards/standards/smirnoff/#toolkitam1bcc-temporary-support-for-toolkit-based-am1-bcc-partial-charges

**Comment by UnixJunkie** [comment]
thanks a lot! Question answered.
