### ISSUE TITLE
Cannot use bespoke-fit to prepare optimization

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-sage#4]
**Expected behaviour**

I expected to generate inputs for optimization by following the instructions here: https://github.com/openforcefield/openff-sage/tree/main/inputs-and-results/optimizations

**Result**

```
(openff-sage) [lilyw7@hpc3-20-19:/pub/lilyw7/pydev/openff-sage/inputs-and-results/optimizations]$ openff-bespoke prepare -i ../../schemas/optimizations/vdw-v1-td-opt-v1.json
LICENSE: Could not open license file "oe_license.txt" in local directory
LICENSE: N.B. OE_LICENSE environment variable is not set
LICENSE: N.B. OE_DIR environment variable is not set
LICENSE: No product keys!
LICENSE: No product keys!
LICENSE: No product keys!
LICENSE: No product keys!
LICENSE: No product keys!
Error: error loading initial parameters

(expected str, bytes or os.PathLike object, not NoneType)
```

No error trace is provided by the client so it is hard to diagnose. I wondered if a force field file was needed, and it did give me a different error:

```
(openff-sage) [lilyw7@hpc3-20-19:/pub/lilyw7/pydev/openff-sage/inputs-and-results/optimizations]$ openff-bespoke prepare -i ../../schemas/optimizations/vdw-v1-td-opt-v1.json -ff /data/homezvol0/lilyw7/miniconda3/envs/openff-sage/lib/python3.9/site-packages/openforcefields/offxml/openff-1.3.0.offxml
Error: the input path did not point to a valid optimization schema

(2 validation errors for OptimizationStageSchema
parameters
  field required (type=value_error.missing)
parameter_hyperparameters
  field required (type=value_error.missing))
```

**Comment by SimonBoothroyd** [comment]
Thanks for raising this @lilyminium - bespokefit is currently in a phase of 'moving fast and breaking things' and this error is caused by the schema stored in this repo not being in the most updated format.

Once a more stable C-F version of bespokefit is available in the next couple of weeks I'll be sure to update this repo so everything aligns with the new models / API!
